<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TeamsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
       $url = 'https://ui-avatars.com/api/?name=';
       $teams = [
            [
                'name' => 'Team 1',
                'tournament_id' => 1,
                'category_id' => 1,
                'league_id' => 1,
                'president_name' => 'President 1',
                'coach_name' => 'Coach 1',
                'phone' => '123456789',
                'email' => 'test@test.com',
                'address' => 'Address 1',
                'image' => $url . 'Team+1&size=64',
            ],
           [
                'name' => 'Team 2',
                'tournament_id' => 1,
                'category_id' => 1,
                'league_id' => 1,
                'president_name' => 'President 2',
                'coach_name' => 'Coach 2',
                'phone' => '123456789',
                'email' => 'test@test.com',
                'address' => 'Address 2',
                'image' => $url . 'Team+2&size=64',
              ],
              [
                'name' => 'Team 3',
                'tournament_id' => 1,
                'category_id' => 1,
                'league_id' => 1,
                'president_name' => 'President 3',
                'coach_name' => 'Coach 3',
                'phone' => '123456789',
                'email' => 'test@test.com',
                'address' => 'Address 3',
                'image' => $url . 'Team+3&size=64',
           ],
           [
                'name' => 'Team 4',
                'tournament_id' => 1,
                'category_id' => 1,
                'league_id' => 1,
                'president_name' => 'President 4',
                'coach_name' => 'Coach 4',
                'phone' => '123456789',
                'email' => 'test@test.com',
                'address' => 'Address 4',
                'image' => $url . 'Team+4&size=64',
           ],
           [
                'name' => 'Team 5',
                'tournament_id' => 1,
                'category_id' => 1,
                'league_id' => 1,
                'president_name' => 'President 5',
                'coach_name' => 'Coach 5',
                'phone' => '123456789',
                'email' => 'test@test.com',
                'address' => 'Address 5',
                'image' => $url . 'Team+5&size=64',
           ],
           [
                'name' => 'Team 6',
                'tournament_id' => 1,
                'category_id' => 1,
                'league_id' => 1,
                'president_name' => 'President 6',
                'coach_name' => 'Coach 6',
                'phone' => '123456789',
                'email' => 'test@test.com',
                'address' => 'Address 6',
                'image' => $url . 'Team+6&size=64',
           ],
           [
                'name' => 'Team 7',
                'tournament_id' => 1,
                'category_id' => 1,
                'league_id' => 1,
                'president_name' => 'President 7',
                'coach_name' => 'Coach 7',
                'phone' => '123456789',
                'email' => 'test@test.com',
                'address' => 'Address 7',
                'image' => $url . 'Team+7&size=64',
           ],
           [
                'name' => 'Team 8',
                'tournament_id' => 1,
                'category_id' => 1,
                'league_id' => 1,
                'president_name' => 'President 8',
                'coach_name' => 'Coach 8',
                'phone' => '123456789',
                'email' => 'test@test.com',
                'address' => 'Address 8',
                'image' => $url . 'Team+8&size=64',
           ],
              [
                 'name' => 'Team 9',
                 'tournament_id' => 1,
                 'category_id' => 1,
                 'league_id' => 1,
                 'president_name' => 'President 9',
                 'coach_name' => 'Coach 9',
                 'phone' => '123456789',
                 'email' => 'test@test.com',
                 'address' => 'Address 9',
                 'image' => $url . 'Team+9&size=64',
              ],
              [

                 'name' => 'Team 10',
                 'tournament_id' => 1,
                 'category_id' => 1,
                 'league_id' => 1,
                 'president_name' => 'President 10',
                 'coach_name' => 'Coach 10',
                 'phone' => '123456789',
                 'email' => 'test@test.com',
                 'address' => 'Address 10',
                 'image' => $url . 'Team+10&size=64',
              ],
           [
                'name' => 'Team 11',
                'tournament_id' => 1,
                'category_id' => 1,
                'league_id' => 1,
                'president_name' => 'President 11',
                'coach_name' => 'Coach 11',
                'phone' => '123456789',
                'email' => 'test@test.com',
                'address' => 'Address 11',
                'image' => $url . 'Team+11&size=64',
           ],
           [
                'name' => 'Team 12',
                'tournament_id' => 1,
                'category_id' => 1,
                'league_id' => 1,
                'president_name' => 'President 12',
                'coach_name' => 'Coach 12',
                'phone' => '123456789',
                'email' => 'test@test.com',
                'address' => 'Address 12',
                'image' => $url . 'Team+12&size=64',
           ],
           [
                'name' => 'Team 13',
                'tournament_id' => 1,
                'category_id' => 1,
                'league_id' => 1,
                'president_name' => 'President 13',
                'coach_name' => 'Coach 13',
                'phone' => '123456789',
                'email' => 'test@test.com',
                'address' => 'Address 13',
                'image' => $url . 'Team+13&size=64',
           ],
           [
                'name' => 'Team 14',
                'tournament_id' => 1,
                'category_id' => 1,
                'league_id' => 1,
                'president_name' => 'President 14',
                'coach_name' => 'Coach 14',
                'phone' => '123456789',
                'email' => 'test@test.com',
                'address' => 'Address 14',
                'image' => $url . 'Team+14&size=64',
           ],
           [
                'name' => 'Team 15',
                'tournament_id' => 1,
                'category_id' => 1,
                'league_id' => 1,
                'president_name' => 'President 15',
                'coach_name' => 'Coach 15',
                'phone' => '123456789',
                'email' => 'test@test.com',
                'address' => 'Address 15',
                'image' => $url . 'Team+15&size=64',
           ],
           [
                'name' => 'Team 16',
                'tournament_id' => 1,
                'category_id' => 1,
                'league_id' => 1,
                'president_name' => 'President 16',
                'coach_name' => 'Coach 16',
                'phone' => '123456789',
                'email' => 'test@test.com',
                'address' => 'Address 16',
                'image' => $url . 'Team+16&size=64',
           ],
              [
                 'name' => 'Team 17',
                 'tournament_id' => 1,
                 'category_id' => 1,
                 'league_id' => 1,
                 'president_name' => 'President 17',
                 'coach_name' => 'Coach 17',
                 'phone' => '123456789',
                 'email' => 'test@test.com',
                 'address' => 'Address 17',
                 'image' => $url . 'Team+17&size=64',
              ],
              [
                 'name' => 'Team 18',
                 'tournament_id' => 1,
                 'category_id' => 1,
                 'league_id' => 1,
                 'president_name' => 'President 18',
                 'coach_name' => 'Coach 18',
                 'phone' => '123456789',
                 'email' => 'test@test.com',
                 'address' => 'Address 18',
                 'image' => $url . 'Team+18&size=64',
              ],
              [
                 'name' => 'Team 19',
                 'tournament_id' => 1,
                 'category_id' => 1,
                 'league_id' => 1,
                 'president_name' => 'President 19',
                 'coach_name' => 'Coach 19',
                 'phone' => '123456789',
                 'email' => 'test@test.com',
                 'address' => 'Address 19',
                 'image' => $url . 'Team+19&size=64',
              ],
              [
                 'name' => 'Team 20',
                 'tournament_id' => 1,
                 'category_id' => 1,
                 'league_id' => 1,
                 'president_name' => 'President 20',
                 'coach_name' => 'Coach 20',
                 'phone' => '123456789',
                 'email' => 'test@test.com',
                 'address' => 'Address 20',
                 'image' => $url . 'Team+20&size=64',
              ],

        ];

        foreach($teams as $team){
           DB::table('teams')->insert($team);
        }
    }
}
