# .github/workflows/deploy.yml
name: Deploy

on:
  workflow_run:
    workflows: [ "Run Laravel Tests" ]
    types:
      - completed

jobs:
  deploy:
    environment: production
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy App
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -Eeuo pipefail
            trap 'echo "[deploy] Failed at line $LINENO" >&2' ERR
            cd "${{ secrets.DEPLOY_PATH }}"

            # Ensure correct branch and up-to-date code
            git fetch --prune
            git checkout main
            git pull --ff-only origin main

            # PHP / Composer diagnostics and setup
            echo "PHP: $(php -v | head -n1)"
            if ! command -v composer >/dev/null 2>&1; then
              echo "Composer not found; attempting install..."
              EXPECTED_SIGNATURE=$(curl -s https://composer.github.io/installer.sig)
              php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
              ACTUAL_SIGNATURE=$(php -r "echo hash_file('sha384', 'composer-setup.php');")
              if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]; then echo 'ERROR: Invalid installer signature'; rm composer-setup.php; exit 1; fi
              php composer-setup.php --install-dir=/usr/local/bin --filename=composer --quiet
              rm composer-setup.php
            fi
            echo "Composer: $(composer --version)"
            export COMPOSER_MEMORY_LIMIT=-1

            # Ensure writable directories before any Artisan runs in composer scripts
            mkdir -p storage/logs bootstrap/cache
            chmod -R 775 storage bootstrap/cache || chmod -R 777 storage bootstrap/cache || true

            # Build new .env content without heredoc to avoid EOL issues
            rm -f .env.new
            {
              echo "APP_NAME=${{ vars.APP_NAME || 'Futzo' }}"
              echo "APP_ENV=${{ vars.APP_ENV || 'production' }}"
              echo "APP_DEBUG=${{ vars.APP_DEBUG || 'false' }}"
              echo "APP_URL=${{ vars.APP_URL }}"
              echo
              echo "LOG_CHANNEL=${{ vars.LOG_CHANNEL || 'stack' }}"
              echo "LOG_LEVEL=${{ vars.LOG_LEVEL || 'info' }}"
              echo
              echo "DB_CONNECTION=${{ vars.DB_CONNECTION || 'mysql' }}"
              echo "DB_HOST=${{ vars.DB_HOST }}"
              echo "DB_PORT=${{ vars.DB_PORT || '3306' }}"
              echo "DB_DATABASE=${{ vars.DB_DATABASE }}"
              echo "DB_USERNAME=${{ secrets.DB_USERNAME }}"
              echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}"
              echo
              echo "BROADCAST_DRIVER=${{ vars.BROADCAST_DRIVER || 'log' }}"
              echo "CACHE_DRIVER=${{ vars.CACHE_DRIVER || 'file' }}"
              echo "FILESYSTEM_DISK=${{ vars.FILESYSTEM_DISK || 'local' }}"
              echo "QUEUE_CONNECTION=${{ vars.QUEUE_CONNECTION || 'sync' }}"
              echo "SESSION_DRIVER=${{ vars.SESSION_DRIVER || 'file' }}"
              echo "SESSION_LIFETIME=${{ vars.SESSION_LIFETIME || '120' }}"
              echo "SESSION_DOMAIN=${{ vars.SESSION_DOMAIN }}"
              echo "SESSION_SECURE_COOKIE=${{ vars.SESSION_SECURE_COOKIE || 'true' }}"
              echo
              echo "REDIS_HOST=${{ vars.REDIS_HOST }}"
              echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}"
              echo "REDIS_PORT=${{ vars.REDIS_PORT || '6379' }}"
              echo
              echo "MAIL_MAILER=${{ vars.MAIL_MAILER || 'ses' }}"
              echo "MAIL_HOST=${{ vars.MAIL_HOST }}"
              echo "MAIL_PORT=${{ vars.MAIL_PORT }}"
              echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}"
              echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}"
              echo "MAIL_ENCRYPTION=${{ vars.MAIL_ENCRYPTION || 'tls' }}"
              echo "MAIL_FROM_ADDRESS=${{ vars.MAIL_FROM_ADDRESS }}"
              echo "MAIL_FROM_NAME=${{ vars.APP_NAME }}"
              echo
              echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
              echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
              echo "AWS_DEFAULT_REGION=${{ vars.AWS_DEFAULT_REGION }}"
              echo "AWS_BUCKET=${{ vars.AWS_BUCKET }}"
              echo "AWS_USE_PATH_STYLE_ENDPOINT=${{ vars.AWS_USE_PATH_STYLE_ENDPOINT || 'false' }}"
              echo
              echo "STRIPE_SECRET=${{ secrets.STRIPE_SECRET }}"
              echo
              echo "TWILIO_SID=${{ secrets.TWILIO_SID }}"
              echo "TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }}"
              echo "TWILIO_VERIFY_SID=${{ secrets.TWILIO_VERIFY_SID }}"
              echo "TWILIO_NUMBER=${{ vars.TWILIO_NUMBER }}"
              echo
              echo "META_PIXEL_ID=${{ vars.META_PIXEL_ID }}"
              echo "META_ACCESS_TOKEN=${{ secrets.META_ACCESS_TOKEN }}"
              echo "META_TEST_EVENT_CODE=${{ vars.META_TEST_EVENT_CODE }}"
              echo
              echo "FACEBOOK_CLIENT_ID=${{ vars.FACEBOOK_CLIENT_ID }}"
              echo "FACEBOOK_CLIENT_SECRET=${{ secrets.FACEBOOK_CLIENT_SECRET }}"
              echo "FACEBOOK_REDIRECT_URI=${{ vars.APP_URL }}/auth/facebook/callback"
              echo
              echo "GOOGLE_CLIENT_ID=${{ vars.GOOGLE_CLIENT_ID }}"
              echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}"
              echo "GOOGLE_REDIRECT_URI=${{ vars.APP_URL }}/auth/google/callback"
              echo
              echo "WHATSAPP_TOKEN=${{ secrets.WHATSAPP_TOKEN }}"
              echo "WHATSAPP_PHONE_ID=${{ vars.WHATSAPP_PHONE_ID }}"
              echo "WHATSAPP_ACCOUNT_ID=${{ vars.WHATSAPP_ACCOUNT_ID }}"
              echo "WHATSAPP_URL=${{ vars.WHATSAPP_URL || 'https://graph.facebook.com/v22.0' }}"
              echo
              echo "FRONTEND_URL=${{ vars.FRONTEND_URL }}"
              echo
              echo "SANCTUM_STATEFUL_DOMAINS=${{ vars.SANCTUM_STATEFUL_DOMAINS }}"
            } > .env.new

            # Preserve existing APP_KEY if present
            if [ -f .env ] && grep -q '^APP_KEY=' .env; then
              grep '^APP_KEY=' .env >> .env.new
            fi
            mv .env.new .env

            # Install dependencies
            composer install --no-dev --prefer-dist --no-progress --no-interaction --optimize-autoloader --classmap-authoritative
            # Ensure Cashier is present (fail if missing)
            composer show laravel/cashier >/dev/null 2>&1 || { echo 'ERROR: laravel/cashier not installed'; exit 1; }
            php -r 'exit(class_exists("Laravel\\Cashier\\Cashier")?0:1);' || { echo 'ERROR: Cashier class not found after install'; exit 1; }
            php artisan package:discover --ansi

            # Ensure APP_KEY exists (generate only if missing/empty)
            if ! grep -q '^APP_KEY=' .env || [ -z "$(sed -n 's/^APP_KEY=//p' .env)" ]; then
              php artisan key:generate --force
            fi

            # Run migrations and optimize caches
            php artisan config:clear
            php artisan cache:clear
            php artisan migrate --force --no-interaction
            php artisan route:cache
            php artisan view:cache
            php artisan config:cache
            php artisan storage:link || true
            sudo systemctl restart horizon
          EOF
