name: Run Laravel Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      APP_ENV: testing
      APP_URL: http://localhost
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: testing
      DB_USERNAME: root
      DB_PASSWORD: root
      CACHE_DRIVER: array
      SESSION_DRIVER: array
      QUEUE_CONNECTION: sync
      FILESYSTEM_DISK: local
      MAIL_MAILER: log
      FRONTEND_URL: http://localhost
      # Dummies for third-party services to avoid external calls in CI
      META_PIXEL_ID: dummy
      META_ACCESS_TOKEN: dummy
      META_TEST_EVENT_CODE: dummy
      STRIPE_SECRET: dummy
      TWILIO_SID: dummy
      TWILIO_AUTH_TOKEN: dummy
      TWILIO_VERIFY_SID: dummy
      TWILIO_NUMBER: "+10000000000"
      WHATSAPP_TOKEN: dummy
      WHATSAPP_PHONE_ID: "123"
      WHATSAPP_ACCOUNT_ID: "123"
      WHATSAPP_URL: https://graph.facebook.com/v22.0
      FACEBOOK_CLIENT_ID: dummy
      FACEBOOK_CLIENT_SECRET: dummy
      FACEBOOK_REDIRECT_URI: http://localhost/auth/facebook/callback
      GOOGLE_CLIENT_ID: dummy
      GOOGLE_CLIENT_SECRET: dummy
      GOOGLE_REDIRECT_URI: http://localhost/auth/google/callback
      SANCTUM_STATEFUL_DOMAINS: localhost
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Wait for MySQL
        run: |
          for i in {1..60}; do
            if mysqladmin ping -h 127.0.0.1 -u root --password=root --silent; then
              echo "MySQL is up"; break
            fi
            echo "Waiting for MySQL..."; sleep 2
          done

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan migrate --force

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run Laravel Tests
        run: php artisan test --env=testing
